from collections import OrderedDict

states = OrderedDict([
    ('AK', 'Alaska'),
    ('AL', 'Alabama'),
    ('AR', 'Arkansas'),
    ('AS', 'American Samoa'),
    ('AZ', 'Arizona'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DC', 'District of Columbia'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('GU', 'Guam'),
    ('HI', 'Hawaii'),
    ('IA', 'Iowa'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('MA', 'Massachusetts'),
    ('MD', 'Maryland'),
    ('ME', 'Maine'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MO', 'Missouri'),
    ('MP', 'Northern Mariana Islands'),
    ('MS', 'Mississippi'),
    ('MT', 'Montana'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('NE', 'Nebraska'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NV', 'Nevada'),
    ('NY', 'New York'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('PR', 'Puerto Rico'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VA', 'Virginia'),
    ('VI', 'Virgin Islands'),
    ('VT', 'Vermont'),
    ('WA', 'Washington'),
    ('WI', 'Wisconsin'),
    ('WV', 'West Virginia'),
    ('WY', 'Wyoming'),
])

parties = OrderedDict([
    ('DEM', 'Democratic Party'),
    ('REP', 'Republican Party'),
])
parties_extended = OrderedDict([
    ('AIC', 'American Independent Conservative'),
    ('AIP', 'American Independent Party'),
    ('AMP', 'American Party'),
    ('APF', "American People's Freedom Party"),
    ('CIT', "Citizens' Party"),
    ('CMP', 'Commonwealth Party of the U.S.'),
    ('COM', 'Communist Party'),
    ('CRV', 'Conservative Party'),
    ('CST', 'Constitutional'),
    ('D/C', 'Democratic/Conservative'),
    ('DFL', 'Democratic-Farm-Labor'),
    ('FLP', 'Freedom Labor Party'),
    ('GRE', 'Green Party'),
    ('GWP', 'George Wallace Party'),
    ('HRP', 'Human Rights Party'),
    ('IAP', 'Independent American Party'),
    ('ICD', 'Independent Conserv. Democratic'),
    ('IGD', 'Industrial Government Party'),
    ('IND', 'Independent'),
    ('LAB', 'U.S. Labor Party'),
    ('LBL', 'Liberal Party'),
    ('LBR', 'Labor Party'),
    ('LBU', 'Liberty Union Party'),
    ('LFT', 'Less Federal Taxes'),
    ('LIB', 'Libertarian'),
    ('LRU', 'La Raza Unida'),
    ('NAP', 'Prohibition Party'),
    ('NDP', 'National Democratic Party'),
    ('NLP', 'Natural Law Party'),
    ('PAF', 'Peace and Freedom'),
    ('PFD', 'Peace Freedom Party'),
    ('POP', 'People Over Politics'),
    ('PPD', 'Protest, Progress, Dignity'),
    ('PPY', "People's Party"),
    ('REF', 'Reform Party'),
    ('RTL', 'Right to Life'),
    ('SLP', 'Socialist Labor Party'),
    ('SUS', 'Socialist Party U.S.A.'),
    ('SWP', 'Socialist Workers Party'),
    ('THD', 'Theo-Dem'),
    ('TWR', 'Taxpayers Without Representation'),
    ('TX', 'Taxpayers'),
    ('USP', "U.S. People's Party"),
])

report_types = OrderedDict([
    ('M1', 'January Monthly'),
    ('M2', 'February Monthly'),
    ('M3', 'March Monthly'),
    ('M4', 'April Monthly'),
    ('M5', 'May Monthly'),
    ('M6', 'June Monthly'),
    ('M7', 'July Monthly'),
    ('M8', 'August Monthly'),
    ('M9', 'September Monthly'),
    ('M10', 'October Monthly'),
    ('M11', 'November Monthly'),
    ('M12', 'December Monthly'),
    ('YE', 'Year-end'),
    ('Q1', 'April Quarterly'),
    ('Q2', 'July Quarterly'),
    ('Q3', 'October Quarterly'),
    ('MY', 'Mid-year Report'),
    ('YE', 'Year-end'),    
    ('12P', 'Pre-Primary'),
    ('12C', 'Pre-Convention'),
    ('12G', 'Pre-General'),
    ('12R', 'Pre-Runoff'),
    ('12S', 'Pre-Special'),
    ('30G', 'Post-General'),
    ('30R', 'Post-Runoff'),
    ('30S', 'Post-Special'),
    ('30P', 'Post-Primary'),
    ('60D', 'Post-Convention'),
    ('10D', 'Pre-Election (10D)'),
    ('10G', 'Pre-General (10G)'),
    ('10P', 'Pre-Primary (10P)'),
    ('10R', 'Pre-Runoff (10R)'),
    ('10S', 'Pre-Special (10S)'),
    ('30D', 'Post-Election (30D)'),
    ('TER', 'Termination'),
    ('24', '24-Hour Notification'),
    ('48', '48-Hour Notification'),
    ('90D', 'Post-Inaugural'),
    ('90S', 'Post-Inaugural Supplement'),
    ('CA', 'Comprehensive Amendment'),
    ('ADJ', 'Comprehensive Adjusted Amendment'),
    ('M7S', 'July Monthly / Semi-Annual'),
    ('MSA', 'Monthly Semi-Annual Mid-Year'),
    ('MSY', 'Monthly Semi-Annual Year-End'),
    ('MYS', 'Monthly Year-End / Semi-Annual'),
    ('Q2S', 'July Quarterly / Semi-Annual'),
    ('QSA', 'Quarterly Semi-Annual (MY)'),
    ('QYE', 'Quarterly Semi-Annual (YE)'),
    ('QYS', 'Quarterly Year-End / Semi-Annual'),
    ('QMS', 'Quarterly Mid-Year / Semi-Annual'),
])

form_types = OrderedDict([
    ('F1', "Statements Of Organization"),
    ('F1M', "Multicandidate Status"),
    ('F2', "Statements Of Candidacy"),
    ('F3', "Congressional Candidate Financial Reports"),
    ('F3P', "Presidential Financial Reports"),
    ('F3X', "PAC and Party Financial Reports"),
    ('F3L', "Bundled Contributions Reports"),
    ('F4', "Convention Financial Reports"),
    ('F5', "Independent Expenditure Reports and Notices"),
    ('F24', "24/48 Hour Notice Of Independent Expenditures or Coordinated Expenditures"),
    ('F6', "Contributions and Loans Notices"),
    ('F7', "Communication Cost Reports"),
    ('F8', "Debt Settlement Plans"),
    ('F9', "Electioneering Communications Notices"),
    ('F13', "Inaugural Committee Donation Reports"),
    ('F99', "Miscellaneous Submission"),
    ('F10', "Expenditure of Personal Funds Notices"),
    ('F11', "Opposition Personal Funds Notices"),
    ('F12', "Suspension of Increased Limits Notices"),
    ('RFAI', "Request For Additional Information"),
])

amendment_indicators = OrderedDict([
    ('N', 'New'),
    ('A', 'Amended'),
])
amendment_indicators_extended = OrderedDict([
    ('T', 'Terminated'),
    ('C', 'Consolidated'),
    ('M', 'Multi-Candidate'),
    ('S', 'Secondary'),
])
