import re
import locale

from openfecwebapp.api_caller import load_cmte_financials
from openfecwebapp.data_prep.shared import committee_type_map

locale.setlocale(locale.LC_ALL, '')

def _map_committee_financials(vals):
    """
    maps and returns template vars for financial summaries
    from the 'totals' endpoint for use on candidate
    and committee pages
    """
    reports = vals['reports'][0] if vals['reports'] else {}
    totals = vals['totals'][0] if vals['totals'] else {}
    totals_mapped = {}
    value_map = {
        'total_receipts': totals.get('receipts'),
        'total_disbursements': totals.get('disbursements'),
        'total_cash': reports.get('cash_on_hand_end_period'),
        'total_debt': reports.get('debts_owed_by_committee')
    }

    # format totals data in US dollars
    for v in value_map:
        if value_map[v] is not None and value_map[v] != 0:
            totals_mapped[v] = locale.currency(
            value_map[v], grouping=True)

    if reports.get('report_year'):
        totals_mapped['report_year'] = str(int(reports['report_year']))

    # "calculated from" on site
    if reports.get('cycle'):
        cycle_minus_one = str(int(reports['cycle']) - 1)
        totals_mapped['years_totals'] = cycle_minus_one
        totals_mapped['years_totals'] += ' - '
        totals_mapped['years_totals'] += str(reports['cycle'])

    # "source:" on site
    if reports.get('report_type_full'):
        totals_mapped['report_desc'] = re.sub('{.+}',
            '', reports['report_type_full'])

    return totals_mapped

def add_fake_chart_data():
    return {'reports': [
        {
            "all_loans_received_period": 0,
            "all_loans_received_ytd": 0,
            "allocated_federal_election_levin_share_period": 0,
            "beginning_image_number": 13961150105,
            "calendar_ytd": 2013,
            "cash_on_hand_beginning_calendar_ytd": 300481,
            "cash_on_hand_beginning_period": 479020,
            "cash_on_hand_close_ytd": 578513,
            "cash_on_hand_end_period": 578513,
            "committee_id": "C00000422",
            "coordinated_expenditures_by_party_committee_period": 0,
            "coordinated_expenditures_by_party_committee_ytd": 0,
            "cycle": 2014,
            "debts_owed_by_committee": 0,
            "debts_owed_to_committee": 0,
            "end_image_number": 13961150149,
            "fed_candidate_committee_contribution_refunds_ytd": 500,
            "fed_candidate_committee_contributions_period": 5000,
            "fed_candidate_committee_contributions_ytd": 30000,
            "fed_candidate_contribution_refunds_period": 0,
            "independent_expenditures_period": 0,
            "independent_expenditures_ytd": 0,
            "individual_contribution_refunds_period": 683,
            "individual_contribution_refunds_ytd": 683,
            "individual_itemized_contributions_period": 59378,
            "individual_itemized_contributions_ytd": 140753,
            "individual_unitemized_contributions_period": 47814,
            "individual_unitemized_contributions_ytd": 170751,
            "loan_repayments_made_period": 0,
            "loan_repayments_made_ytd": 0,
            "loan_repayments_received_period": 0,
            "loan_repayments_received_ytd": 0,
            "loans_made_period": 0,
            "loans_made_ytd": 0,
            "net_contributions_period": 106509,
            "net_contributions_ytd": 310822,
            "net_operating_expenditures_period": 2018,
            "net_operating_expenditures_ytd": 3292,
            "non_allocated_fed_election_activity_period": 0,
            "non_allocated_fed_election_activity_ytd": 0,
            "nonfed_share_allocated_disbursements_period": 0,
            "offsets_to_operating_expenditures_period": 0,
            "offsets_to_operating_expenditures_ytd": 0,
            "other_disbursements_period": 0,
            "other_disbursements_ytd": 0,
            "other_fed_operating_expenditures_period": 2018,
            "other_fed_operating_expenditures_ytd": 3292,
            "other_fed_receipts_period": 1,
            "other_fed_receipts_ytd": 3,
            "other_political_committee_contribution_refunds_period": 0,
            "other_political_committee_contribution_refunds_ytd": 0,
            "other_political_committee_contributions_period": 0,
            "other_political_committee_contributions_ytd": 0,
            "political_party_committee_contribution_refunds_period": 0,
            "political_party_committee_contribution_refunds_ytd": 0,
            "political_party_committee_contributions_period": 0,
            "political_party_committee_contributions_ytd": 0,
            "report_type": "M3",
            "report_type_full": "March Monthly ",
            "report_year": 2013,
            "shared_fed_activity_nonfed_ytd": 0,
            "shared_fed_activity_period": 0,
            "shared_fed_activity_ytd": 0,
            "shared_fed_operating_expenditures_period": 0,
            "shared_fed_operating_expenditures_ytd": 0,
            "shared_nonfed_operating_expenditures_ytd": 0,
            "subtotal_summary_page_period": 586215,
            "subtotal_summary_ytd": 612489,
            "total_contribution_refunds_period": 683,
            "total_contribution_refunds_ytd": 683,
            "total_contributions_period": 107193,
            "total_contributions_ytd": 311505,
            "total_disbursements_period": 7701,
            "total_disbursements_summary_page_period": 7701,
            "total_disbursements_summary_page_ytd": 33976,
            "total_disbursements_ytd": 33976,
            "total_fed_disbursements_period": 7701,
            "total_fed_disbursements_ytd": 33976,
            "total_fed_elect_activity_period": 0,
            "total_fed_election_activity_ytd": 0,
            "total_fed_operating_expenditures_period": 2018,
            "total_fed_operating_expenditures_ytd": 3292,
            "total_fed_receipts_period": 107194,
            "total_fed_receipts_ytd": 312008,
            "total_individual_contributions": 107193,
            "total_individual_contributions_ytd": 311505,
            "total_nonfed_transfers_period": 0,
            "total_nonfed_transfers_ytd": 0,
            "total_operating_expenditures_period": 2018,
            "total_operating_expenditures_ytd": 3292,
            "total_receipts_period": 107194,
            "total_receipts_summary_page_period": 107194,
            "total_receipts_summary_page_ytd": 312008,
            "total_receipts_ytd": 312008,
            "transfers_from_affiliated_party_period": 0,
            "transfers_from_affiliated_party_ytd": 0,
            "transfers_from_nonfed_account_period": 0,
            "transfers_from_nonfed_account_ytd": 0,
            "transfers_from_nonfed_levin_period": 0,
            "transfers_from_nonfed_levin_ytd": 0,
            "transfers_to_affiliated_committee_period": 0,
            "transfers_to_affilitated_committees_ytd": 0
        },
        {
            "all_loans_received_period": 0,
            "all_loans_received_ytd": 0,
            "allocated_federal_election_levin_share_period": 0,
            "beginning_image_number": 13940513590,
            "calendar_ytd": 2013,
            "cash_on_hand_beginning_calendar_ytd": 300481,
            "cash_on_hand_beginning_period": 578513,
            "cash_on_hand_close_ytd": 658407,
            "cash_on_hand_end_period": 658407,
            "committee_id": "C00000422",
            "coordinated_expenditures_by_party_committee_period": 0,
            "coordinated_expenditures_by_party_committee_ytd": 0,
            "cycle": 2014,
            "debts_owed_by_committee": 0,
            "debts_owed_to_committee": 0,
            "end_image_number": 13940513668,
            "fed_candidate_committee_contribution_refunds_ytd": 500,
            "fed_candidate_committee_contributions_period": 60500,
            "fed_candidate_committee_contributions_ytd": 90500,
            "fed_candidate_contribution_refunds_period": 0,
            "independent_expenditures_period": 0,
            "independent_expenditures_ytd": 0,
            "individual_contribution_refunds_period": 500,
            "individual_contribution_refunds_ytd": 1183,
            "individual_itemized_contributions_period": 54276,
            "individual_itemized_contributions_ytd": 195029,
            "individual_unitemized_contributions_period": 87845,
            "individual_unitemized_contributions_ytd": 258597,
            "loan_repayments_made_period": 0,
            "loan_repayments_made_ytd": 0,
            "loan_repayments_received_period": 0,
            "loan_repayments_received_ytd": 0,
            "loans_made_period": 0,
            "loans_made_ytd": 0,
            "net_contributions_period": 141622,
            "net_contributions_ytd": 452444,
            "net_operating_expenditures_period": 1231,
            "net_operating_expenditures_ytd": 4524,
            "non_allocated_fed_election_activity_period": 0,
            "non_allocated_fed_election_activity_ytd": 0,
            "nonfed_share_allocated_disbursements_period": 0,
            "offsets_to_operating_expenditures_period": 0,
            "offsets_to_operating_expenditures_ytd": 0,
            "other_disbursements_period": 0,
            "other_disbursements_ytd": 0,
            "other_fed_operating_expenditures_period": 1231,
            "other_fed_operating_expenditures_ytd": 4524,
            "other_fed_receipts_period": 2,
            "other_fed_receipts_ytd": 6,
            "other_political_committee_contribution_refunds_period": 0,
            "other_political_committee_contribution_refunds_ytd": 0,
            "other_political_committee_contributions_period": 0,
            "other_political_committee_contributions_ytd": 0,
            "political_party_committee_contribution_refunds_period": 0,
            "political_party_committee_contribution_refunds_ytd": 0,
            "political_party_committee_contributions_period": 0,
            "political_party_committee_contributions_ytd": 0,
            "report_type": "M4",
            "report_type_full": "April Monthly ",
            "report_year": 2013,
            "shared_fed_activity_nonfed_ytd": 0,
            "shared_fed_activity_period": 0,
            "shared_fed_activity_ytd": 0,
            "shared_fed_operating_expenditures_period": 0,
            "shared_fed_operating_expenditures_ytd": 0,
            "shared_nonfed_operating_expenditures_ytd": 0,
            "subtotal_summary_page_period": 720638,
            "subtotal_summary_ytd": 754614,
            "total_contribution_refunds_period": 500,
            "total_contribution_refunds_ytd": 1183,
            "total_contributions_period": 142122,
            "total_contributions_ytd": 453627,
            "total_disbursements_period": 62231,
            "total_disbursements_summary_page_period": 62231,
            "total_disbursements_summary_page_ytd": 96207,
            "total_disbursements_ytd": 96207,
            "total_fed_disbursements_period": 62231,
            "total_fed_disbursements_ytd": 96207,
            "total_fed_elect_activity_period": 0,
            "total_fed_election_activity_ytd": 0,
            "total_fed_operating_expenditures_period": 1231,
            "total_fed_operating_expenditures_ytd": 4524,
            "total_fed_receipts_period": 142125,
            "total_fed_receipts_ytd": 454133,
            "total_individual_contributions": 142122,
            "total_individual_contributions_ytd": 453627,
            "total_nonfed_transfers_period": 0,
            "total_nonfed_transfers_ytd": 0,
            "total_operating_expenditures_period": 1231,
            "total_operating_expenditures_ytd": 4524,
            "total_receipts_period": 142125,
            "total_receipts_summary_page_period": 142125,
            "total_receipts_summary_page_ytd": 454133,
            "total_receipts_ytd": 454133,
            "transfers_from_affiliated_party_period": 0,
            "transfers_from_affiliated_party_ytd": 0,
            "transfers_from_nonfed_account_period": 0,
            "transfers_from_nonfed_account_ytd": 0,
            "transfers_from_nonfed_levin_period": 0,
            "transfers_from_nonfed_levin_ytd": 0,
            "transfers_to_affiliated_committee_period": 0,
            "transfers_to_affilitated_committees_ytd": 0
        },
        {
            "all_loans_received_period": 0,
            "all_loans_received_ytd": 0,
            "allocated_federal_election_levin_share_period": 0,
            "beginning_image_number": 13964501110,
            "calendar_ytd": 2013,
            "cash_on_hand_beginning_calendar_ytd": 300481,
            "cash_on_hand_beginning_period": 836709,
            "cash_on_hand_close_ytd": 844699,
            "cash_on_hand_end_period": 844699,
            "committee_id": "C00000422",
            "coordinated_expenditures_by_party_committee_period": 0,
            "coordinated_expenditures_by_party_committee_ytd": 0,
            "cycle": 2014,
            "debts_owed_by_committee": 0,
            "debts_owed_to_committee": 0,
            "end_image_number": 13964501206,
            "expire_date": "Mon, 24 Nov 2014 16:53:41 -0000",
            "fed_candidate_committee_contribution_refunds_ytd": 500,
            "fed_candidate_committee_contributions_period": 33000,
            "fed_candidate_committee_contributions_ytd": 219200,
            "fed_candidate_contribution_refunds_period": 0,
            "independent_expenditures_period": 0,
            "independent_expenditures_ytd": 0,
            "individual_contribution_refunds_period": 83,
            "individual_contribution_refunds_ytd": 2466,
            "individual_itemized_contributions_period": 22414,
            "individual_itemized_contributions_ytd": 386463,
            "individual_unitemized_contributions_period": 19403,
            "individual_unitemized_contributions_ytd": 387693,
            "loan_repayments_made_period": 0,
            "loan_repayments_made_ytd": 0,
            "loan_repayments_received_period": 0,
            "loan_repayments_received_ytd": 0,
            "loans_made_period": 0,
            "loans_made_ytd": 0,
            "net_contributions_period": 41734,
            "net_contributions_ytd": 771690,
            "net_operating_expenditures_period": 749,
            "net_operating_expenditures_ytd": 8798,
            "non_allocated_fed_election_activity_period": 0,
            "non_allocated_fed_election_activity_ytd": 0,
            "nonfed_share_allocated_disbursements_period": 0,
            "offsets_to_operating_expenditures_period": 0,
            "offsets_to_operating_expenditures_ytd": 0,
            "other_disbursements_period": 0,
            "other_disbursements_ytd": 1408,
            "other_fed_operating_expenditures_period": 749,
            "other_fed_operating_expenditures_ytd": 8798,
            "other_fed_receipts_period": 5,
            "other_fed_receipts_ytd": 1434,
            "other_political_committee_contribution_refunds_period": 0,
            "other_political_committee_contribution_refunds_ytd": 0,
            "other_political_committee_contributions_period": 0,
            "other_political_committee_contributions_ytd": 0,
            "political_party_committee_contribution_refunds_period": 0,
            "political_party_committee_contribution_refunds_ytd": 0,
            "political_party_committee_contributions_period": 0,
            "political_party_committee_contributions_ytd": 0,
            "report_type": "M8",
            "report_type_full": "August Monthly ",
            "report_year": 2013,
            "shared_fed_activity_nonfed_ytd": 0,
            "shared_fed_activity_period": 0,
            "shared_fed_activity_ytd": 0,
            "shared_fed_operating_expenditures_period": 0,
            "shared_fed_operating_expenditures_ytd": 0,
            "shared_nonfed_operating_expenditures_ytd": 0,
            "subtotal_summary_page_period": 878532,
            "subtotal_summary_ytd": 1076573,
            "total_contribution_refunds_period": 83,
            "total_contribution_refunds_ytd": 2466,
            "total_contributions_period": 41817,
            "total_contributions_ytd": 774157,
            "total_disbursements_period": 33832,
            "total_disbursements_summary_page_period": 33832,
            "total_disbursements_summary_page_ytd": 231873,
            "total_disbursements_ytd": 231873,
            "total_fed_disbursements_period": 33832,
            "total_fed_disbursements_ytd": 231873,
            "total_fed_elect_activity_period": 0,
            "total_fed_election_activity_ytd": 0,
            "total_fed_operating_expenditures_period": 749,
            "total_fed_operating_expenditures_ytd": 8798,
            "total_fed_receipts_period": 41823,
            "total_fed_receipts_ytd": 776092,
            "total_individual_contributions": 41817,
            "total_individual_contributions_ytd": 774157,
            "total_nonfed_transfers_period": 0,
            "total_nonfed_transfers_ytd": 0,
            "total_operating_expenditures_period": 749,
            "total_operating_expenditures_ytd": 8798,
            "total_receipts_period": 41823,
            "total_receipts_summary_page_period": 41823,
            "total_receipts_summary_page_ytd": 776092,
            "total_receipts_ytd": 776092,
            "transfers_from_affiliated_party_period": 0,
            "transfers_from_affiliated_party_ytd": 0,
            "transfers_from_nonfed_account_period": 0,
            "transfers_from_nonfed_account_ytd": 0,
            "transfers_from_nonfed_levin_period": 0,
            "transfers_from_nonfed_levin_ytd": 0,
            "transfers_to_affiliated_committee_period": 0,
            "transfers_to_affilitated_committees_ytd": 0
        },
        {
            "all_loans_received_period": 0,
            "all_loans_received_ytd": 0,
            "allocated_federal_election_levin_share_period": 0,
            "beginning_image_number": 13964502426,
            "calendar_ytd": 2013,
            "cash_on_hand_beginning_calendar_ytd": 300481,
            "cash_on_hand_beginning_period": 836709,
            "cash_on_hand_close_ytd": 844699,
            "cash_on_hand_end_period": 844699,
            "committee_id": "C00000422",
            "coordinated_expenditures_by_party_committee_period": 0,
            "coordinated_expenditures_by_party_committee_ytd": 0,
            "cycle": 2014,
            "debts_owed_by_committee": 0,
            "debts_owed_to_committee": 0,
            "end_image_number": 13964502523,
            "fed_candidate_committee_contribution_refunds_ytd": 500,
            "fed_candidate_committee_contributions_period": 33000,
            "fed_candidate_committee_contributions_ytd": 219200,
            "fed_candidate_contribution_refunds_period": 0,
            "independent_expenditures_period": 0,
            "independent_expenditures_ytd": 0,
            "individual_contribution_refunds_period": 83,
            "individual_contribution_refunds_ytd": 2466,
            "individual_itemized_contributions_period": 22435,
            "individual_itemized_contributions_ytd": 386484,
            "individual_unitemized_contributions_period": 19382,
            "individual_unitemized_contributions_ytd": 387673,
            "loan_repayments_made_period": 0,
            "loan_repayments_made_ytd": 0,
            "loan_repayments_received_period": 0,
            "loan_repayments_received_ytd": 0,
            "loans_made_period": 0,
            "loans_made_ytd": 0,
            "net_contributions_period": 41734,
            "net_contributions_ytd": 771690,
            "net_operating_expenditures_period": 749,
            "net_operating_expenditures_ytd": 8798,
            "non_allocated_fed_election_activity_period": 0,
            "non_allocated_fed_election_activity_ytd": 0,
            "nonfed_share_allocated_disbursements_period": 0,
            "offsets_to_operating_expenditures_period": 0,
            "offsets_to_operating_expenditures_ytd": 0,
            "other_disbursements_period": 0,
            "other_disbursements_ytd": 1408,
            "other_fed_operating_expenditures_period": 749,
            "other_fed_operating_expenditures_ytd": 8798,
            "other_fed_receipts_period": 5,
            "other_fed_receipts_ytd": 1434,
            "other_political_committee_contribution_refunds_period": 0,
            "other_political_committee_contribution_refunds_ytd": 0,
            "other_political_committee_contributions_period": 0,
            "other_political_committee_contributions_ytd": 0,
            "political_party_committee_contribution_refunds_period": 0,
            "political_party_committee_contribution_refunds_ytd": 0,
            "political_party_committee_contributions_period": 0,
            "political_party_committee_contributions_ytd": 0,
            "report_type": "M8",
            "report_type_full": "August Monthly ",
            "report_year": 2013,
            "shared_fed_activity_nonfed_ytd": 0,
            "shared_fed_activity_period": 0,
            "shared_fed_activity_ytd": 0,
            "shared_fed_operating_expenditures_period": 0,
            "shared_fed_operating_expenditures_ytd": 0,
            "shared_nonfed_operating_expenditures_ytd": 0,
            "subtotal_summary_page_period": 878532,
            "subtotal_summary_ytd": 1076573,
            "total_contribution_refunds_period": 83,
            "total_contribution_refunds_ytd": 2466,
            "total_contributions_period": 41817,
            "total_contributions_ytd": 774157,
            "total_disbursements_period": 33832,
            "total_disbursements_summary_page_period": 33832,
            "total_disbursements_summary_page_ytd": 231873,
            "total_disbursements_ytd": 231873,
            "total_fed_disbursements_period": 33832,
            "total_fed_disbursements_ytd": 231873,
            "total_fed_elect_activity_period": 0,
            "total_fed_election_activity_ytd": 0,
            "total_fed_operating_expenditures_period": 749,
            "total_fed_operating_expenditures_ytd": 8798,
            "total_fed_receipts_period": 41823,
            "total_fed_receipts_ytd": 776092,
            "total_individual_contributions": 41817,
            "total_individual_contributions_ytd": 774157,
            "total_nonfed_transfers_period": 0,
            "total_nonfed_transfers_ytd": 0,
            "total_operating_expenditures_period": 749,
            "total_operating_expenditures_ytd": 8798,
            "total_receipts_period": 41823,
            "total_receipts_summary_page_period": 41823,
            "total_receipts_summary_page_ytd": 776092,
            "total_receipts_ytd": 776092,
            "transfers_from_affiliated_party_period": 0,
            "transfers_from_affiliated_party_ytd": 0,
            "transfers_from_nonfed_account_period": 0,
            "transfers_from_nonfed_account_ytd": 0,
            "transfers_from_nonfed_levin_period": 0,
            "transfers_from_nonfed_levin_ytd": 0,
            "transfers_to_affiliated_committee_period": 0,
            "transfers_to_affilitated_committees_ytd": 0
        },
        {
            "all_loans_received_period": 0,
            "all_loans_received_ytd": 0,
            "allocated_federal_election_levin_share_period": 0,
            "beginning_image_number": 14940031450,
            "calendar_ytd": 2013,
            "cash_on_hand_beginning_calendar_ytd": 300481,
            "cash_on_hand_beginning_period": 1074621,
            "cash_on_hand_close_ytd": 1105120,
            "cash_on_hand_end_period": 1105120,
            "committee_id": "C00000422",
            "coordinated_expenditures_by_party_committee_period": 0,
            "coordinated_expenditures_by_party_committee_ytd": 0,
            "cycle": 2014,
            "debts_owed_by_committee": 0,
            "debts_owed_to_committee": 0,
            "end_image_number": 14940031550,
            "fed_candidate_committee_contribution_refunds_ytd": 500,
            "fed_candidate_committee_contributions_period": 17500,
            "fed_candidate_committee_contributions_ytd": 315700,
            "fed_candidate_contribution_refunds_period": 0,
            "independent_expenditures_period": 0,
            "independent_expenditures_ytd": 0,
            "individual_contribution_refunds_period": 0,
            "individual_contribution_refunds_ytd": 4966,
            "individual_itemized_contributions_period": 23606,
            "individual_itemized_contributions_ytd": 600218,
            "individual_unitemized_contributions_period": 25017,
            "individual_unitemized_contributions_ytd": 537896,
            "loan_repayments_made_period": 0,
            "loan_repayments_made_ytd": 0,
            "loan_repayments_received_period": 0,
            "loan_repayments_received_ytd": 0,
            "loans_made_period": 0,
            "loans_made_ytd": 0,
            "net_contributions_period": 48624,
            "net_contributions_ytd": 1133148,
            "net_operating_expenditures_period": 636,
            "net_operating_expenditures_ytd": 13374,
            "non_allocated_fed_election_activity_period": 0,
            "non_allocated_fed_election_activity_ytd": 0,
            "nonfed_share_allocated_disbursements_period": 0,
            "offsets_to_operating_expenditures_period": 0,
            "offsets_to_operating_expenditures_ytd": 0,
            "other_disbursements_period": 0,
            "other_disbursements_ytd": 1408,
            "other_fed_operating_expenditures_period": 636,
            "other_fed_operating_expenditures_ytd": 13374,
            "other_fed_receipts_period": 11,
            "other_fed_receipts_ytd": 1473,
            "other_political_committee_contribution_refunds_period": 0,
            "other_political_committee_contribution_refunds_ytd": 0,
            "other_political_committee_contributions_period": 0,
            "other_political_committee_contributions_ytd": 0,
            "political_party_committee_contribution_refunds_period": 0,
            "political_party_committee_contribution_refunds_ytd": 0,
            "political_party_committee_contributions_period": 0,
            "political_party_committee_contributions_ytd": 0,
            "report_type": "YE",
            "report_type_full": "Year-end {One of 4 valid Report Codes on Form 5, RptCode} ",
            "report_year": 2013,
            "shared_fed_activity_nonfed_ytd": 0,
            "shared_fed_activity_period": 0,
            "shared_fed_activity_ytd": 0,
            "shared_fed_operating_expenditures_period": 0,
            "shared_fed_operating_expenditures_ytd": 0,
            "shared_nonfed_operating_expenditures_ytd": 0,
            "subtotal_summary_page_period": 1123256,
            "subtotal_summary_ytd": 1440570,
            "total_contribution_refunds_period": 0,
            "total_contribution_refunds_ytd": 4966,
            "total_contributions_period": 48624,
            "total_contributions_ytd": 1138115,
            "total_disbursements_period": 18136,
            "total_disbursements_summary_page_period": 18136,
            "total_disbursements_summary_page_ytd": 335449,
            "total_disbursements_ytd": 335449,
            "total_fed_disbursements_period": 18136,
            "total_fed_disbursements_ytd": 335449,
            "total_fed_elect_activity_period": 0,
            "total_fed_election_activity_ytd": 0,
            "total_fed_operating_expenditures_period": 636,
            "total_fed_operating_expenditures_ytd": 13374,
            "total_fed_receipts_period": 48635,
            "total_fed_receipts_ytd": 1140088,
            "total_individual_contributions": 48624,
            "total_individual_contributions_ytd": 1138115,
            "total_nonfed_transfers_period": 0,
            "total_nonfed_transfers_ytd": 0,
            "total_operating_expenditures_period": 636,
            "total_operating_expenditures_ytd": 13374,
            "total_receipts_period": 48635,
            "total_receipts_summary_page_period": 48635,
            "total_receipts_summary_page_ytd": 1140088,
            "total_receipts_ytd": 1140088,
            "transfers_from_affiliated_party_period": 0,
            "transfers_from_affiliated_party_ytd": 0,
            "transfers_from_nonfed_account_period": 0,
            "transfers_from_nonfed_account_ytd": 0,
            "transfers_from_nonfed_levin_period": 0,
            "transfers_from_nonfed_levin_ytd": 0,
            "transfers_to_affiliated_committee_period": 0,
            "transfers_to_affilitated_committees_ytd": 0
        },
        {
            "all_loans_received_period": 0,
            "all_loans_received_ytd": 0,
            "allocated_federal_election_levin_share_period": 0,
            "beginning_image_number": 14978099474,
            "calendar_ytd": 2014,
            "cash_on_hand_beginning_calendar_ytd": 1105120,
            "cash_on_hand_beginning_period": 765825,
            "cash_on_hand_close_ytd": 556924,
            "cash_on_hand_end_period": 556924,
            "committee_id": "C00000422",
            "coordinated_expenditures_by_party_committee_period": 0,
            "coordinated_expenditures_by_party_committee_ytd": 0,
            "cycle": 2014,
            "debts_owed_by_committee": 0,
            "debts_owed_to_committee": 0,
            "end_image_number": 14978099613,
            "fed_candidate_committee_contribution_refunds_ytd": 1700,
            "fed_candidate_committee_contributions_period": 264000,
            "fed_candidate_committee_contributions_ytd": 1439300,
            "fed_candidate_contribution_refunds_period": 0,
            "independent_expenditures_period": 0,
            "independent_expenditures_ytd": 0,
            "individual_contribution_refunds_period": 541,
            "individual_contribution_refunds_ytd": 1333,
            "individual_itemized_contributions_period": 35436,
            "individual_itemized_contributions_ytd": 478626,
            "individual_unitemized_contributions_period": 21126,
            "individual_unitemized_contributions_ytd": 423174,
            "loan_repayments_made_period": 0,
            "loan_repayments_made_ytd": 0,
            "loan_repayments_received_period": 0,
            "loan_repayments_received_ytd": 0,
            "loans_made_period": 0,
            "loans_made_ytd": 0,
            "net_contributions_period": 56021,
            "net_contributions_ytd": 900466,
            "net_operating_expenditures_period": 929,
            "net_operating_expenditures_ytd": 11027,
            "non_allocated_fed_election_activity_period": 0,
            "non_allocated_fed_election_activity_ytd": 0,
            "nonfed_share_allocated_disbursements_period": 0,
            "offsets_to_operating_expenditures_period": 0,
            "offsets_to_operating_expenditures_ytd": 0,
            "other_disbursements_period": 0,
            "other_disbursements_ytd": 1500,
            "other_fed_operating_expenditures_period": 929,
            "other_fed_operating_expenditures_ytd": 11027,
            "other_fed_receipts_period": 7,
            "other_fed_receipts_ytd": 1587,
            "other_political_committee_contribution_refunds_period": 0,
            "other_political_committee_contribution_refunds_ytd": 0,
            "other_political_committee_contributions_period": 0,
            "other_political_committee_contributions_ytd": 0,
            "political_party_committee_contribution_refunds_period": 0,
            "political_party_committee_contribution_refunds_ytd": 0,
            "political_party_committee_contributions_period": 0,
            "political_party_committee_contributions_ytd": 0,
            "report_type": "M10",
            "report_type_full": "October Monthly ",
            "report_year": 2014,
            "shared_fed_activity_nonfed_ytd": 0,
            "shared_fed_activity_period": 0,
            "shared_fed_activity_ytd": 0,
            "shared_fed_operating_expenditures_period": 0,
            "shared_fed_operating_expenditures_ytd": 0,
            "shared_nonfed_operating_expenditures_ytd": 0,
            "subtotal_summary_page_period": 822396,
            "subtotal_summary_ytd": 2010207,
            "total_contribution_refunds_period": 541,
            "total_contribution_refunds_ytd": 1333,
            "total_contributions_period": 56563,
            "total_contributions_ytd": 901800,
            "total_disbursements_period": 265471,
            "total_disbursements_summary_page_period": 265471,
            "total_disbursements_summary_page_ytd": 1453283,
            "total_disbursements_ytd": 1453283,
            "total_fed_disbursements_period": 265471,
            "total_fed_disbursements_ytd": 1453283,
            "total_fed_elect_activity_period": 0,
            "total_fed_election_activity_ytd": 0,
            "total_fed_operating_expenditures_period": 929,
            "total_fed_operating_expenditures_ytd": 11027,
            "total_fed_receipts_period": 56570,
            "total_fed_receipts_ytd": 905087,
            "total_individual_contributions": 56563,
            "total_individual_contributions_ytd": 901800,
            "total_nonfed_transfers_period": 0,
            "total_nonfed_transfers_ytd": 0,
            "total_operating_expenditures_period": 929,
            "total_operating_expenditures_ytd": 11027,
            "total_receipts_period": 56570,
            "total_receipts_summary_page_period": 56570,
            "total_receipts_summary_page_ytd": 905087,
            "total_receipts_ytd": 905087,
            "transfers_from_affiliated_party_period": 0,
            "transfers_from_affiliated_party_ytd": 0,
            "transfers_from_nonfed_account_period": 0,
            "transfers_from_nonfed_account_ytd": 0,
            "transfers_from_nonfed_levin_period": 0,
            "transfers_from_nonfed_levin_ytd": 0,
            "transfers_to_affiliated_committee_period": 0,
            "transfers_to_affilitated_committees_ytd": 122
        }]}

def add_cmte_financial_data(context, data_type):
    full_cmtes = {}
    cmte_designation_map = {
        'P': 'primary_committee',
        'A': 'authorized_committees',
        'D': 'leadership_committees',
        'J': 'joint_committees'
    }

    if data_type == 'candidate':
        full_cmtes['primary_committee'] = []
        full_cmtes['authorized_committees'] = []
        full_cmtes['leadership_committees'] = []
        full_cmtes['joint_committees'] = []
        candidate = context
        cmtes = candidate.get('committees', [])
        for cmte in cmtes:
            if cmte.get('committee_designation') in ['P', 'A', 'D']:
                cmte.update(load_cmte_financials(cmte['committee_id']))
                cmte.update(_map_committee_financials(cmte))
                tmpl_group = cmte_designation_map[
                    cmte['committee_designation']]
                cmte.update(add_fake_chart_data())
                full_cmtes[tmpl_group].append(cmte)
            elif cmte['committee_designation'] is 'J':
                full_cmtes['joint_committees'].append(cmte)
            else:
                pass
    elif data_type == 'committee':
        cmte = context
        if cmte.get('committee_id'):
            cmte.update(load_cmte_financials(cmte['committee_id']))
            cmte.update(_map_committee_financials(cmte))
            cmte.update(add_fake_chart_data())
        full_cmtes = {'financial_summary': cmte}
    else:
        pass
    return full_cmtes
